---

- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  vars:
    ocp_version: 4.1.13
  connection: local
  become: yes
  tasks:

  - name: Download and unpack Openshift 4 client
    unarchive:
      src: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocp_version }}/openshift-client-linux-{{ ocp_version }}.tar.gz
      dest: /usr/local/bin
      remote_src: yes

  - name: Download and unpack Openshift 4 installer
    unarchive:
      src: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocp_version }}/openshift-install-linux-{{ ocp_version }}.tar.gz
      dest: /usr/local/bin
      remote_src: yes

  - name: Download and unpack AWS CLI
    shell: "curl 'https://s3.amazonaws.com/aws-cli/awscli-bundle.zip' -o 'awscli-bundle.zip'"
    shell: "unzip awscli-bundle.zip"
    shell: "awscli-bundle/install -i /usr/local/aws -b /bin/aws"


  - name: Install a list of Dev tools
    yum:
      name:
        - wget
        - curl
        - git
        - httpd-tools
      state: present

