---

- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  vars:
    client_link: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.3.13/openshift-client-linux-4.3.13.tar.gz
    install_link: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.3.13/openshift-install-linux-4.3.13.tar.gz
  connection: local
  become: yes
  tasks:

  - debug:
      msg:
      - "Install Link: {{ client_link }}"
      - "Client Link: {{ install_link }}"

  - name: Download and unpack Openshift 4 client
    unarchive:
      src: "{{ client_link }}"
      dest: /usr/bin
      remote_src: yes

  - name: Download and unpack Openshift 4 installer
    unarchive:
      src: "{{ install_link }}"
      dest: /usr/bin
      remote_src: yes

  - name: Setup oc completion
    shell: "oc completion bash >/etc/bash_completion.d/openshift"

  - name: Download and unpack AWS CLI
    unarchive:
      src: https://s3.amazonaws.com/aws-cli/awscli-bundle.zip
      dest: ./
      remote_src: yes
    tags: aws

  - name: Install AWS CLI
    shell: "awscli-bundle/install -i /usr/local/aws -b /bin/aws"
    tags: aws

  - name: Cleanup AWS CLI files
    file:
      path: awscli-bundle
      state: absent
    tags: aws

  - name: Install a list of Dev tools
    yum:
      name:
        - wget
        - curl
        - git
        - httpd-tools
      state: present
